check aborting workflow

diff --git a/.github/workflows/feelthenotes-app.yml b/.github/workflows/feelthenotes-app.yml
--- a/.github/workflows/feelthenotes-app.yml
+++ b/.github/workflows/feelthenotes-app.yml
@@ -72,4 +72,4 @@ jobs:
             docker compose pull
             docker compose up -d --force-recreate
             sleep 65 && docker compose ps feelthenotes-app --status="running" | grep "running (healthy)"
-            if [ $? = 0 ]; then echo "Service is running and healthy"; else echo "Service is unhealthy. Aborting job..." exit 1; fi
+            if [ $? = 0 ]; then echo "Service is running and healthy"; else echo "Service is unhealthy. Aborting job..." && exit 1; fi
